### ISSUE TITLE
Vagueness with city

### ISSUE THREAD

**Issue by 676339784** [Uncleleech/weather-wrapper#1]
For example I live in San Jose, USA but the script thinks that I live in the Mexican San Jose as seen [here](https://a.pomf.cat/yypzpo.png). It might also apply with different cities that also share the same name (e.g. Springfield, Franklin).

**Comment by 676339784** [comment]
Never mind, wttr.in also thinks I am in Mexico...

**Comment by snus-kin** [comment]
This is a problem with wttr.in, as a workaround I'd suggest using zip codes or something like San_Jose_USA with the -c option until I create a way to have a config file with defaults.
